# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/reporting"

# KB portal info
has_kb_portal: true
old_kb_portal_link: https://www.telerik.com/support/kb/reporting

# Exclude files which should not be in the output
exclude: [README.md,Gemfile,Gemfile.lock,api_sort.rb,build_kb.rb,switch-ruby.cmd,report-designer-translations]
exclude_navigation: [knowledge-base/*]
navigation:
## List your directory names and order here, like this:   
    knowledge-base:
        title: "Knowledge Base"

## The application virtual path
baseurl: /reporting

## The product name
productName: "Telerik Reporting"

## Progress NPM Registry
registry_url: 'https://registry.npm.telerik.com/'

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        product: "reporting"
        editable: true

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# Feedback Form Google Sheet ID
ff-sheet-id: '1oqaFdgKdIlX6pbd7aeptzbAUv0tfzrC3UwaubBeEwcg'

# The google services configuration
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:zzabynuukmu'
#google_custom_kb_search: '001595215763381649090:2tjzdeu8y54'
gcs_api_key: 'AIzaSyCcGn_7eOPUgwFwAVq1GuypE_IknfYCCtE'

edit_repo_url: https://github.com/telerik/reporting-docs/edit/master
product: "Telerik Reporting"
product_url: https://www.telerik.com/reporting
platform: reporting
download: http://www.telerik.com/products/reporting/download.aspx
nav:
  "Demos": https://demos.telerik.com/reporting
  "Release History": https://www.telerik.com/support/whats-new/reporting/release-history
  "About": http://www.telerik.com/reporting
  "Pricing": https://www.telerik.com/purchase/individual/reporting.aspx

footer:
-
  title: "Getting Started"
  links:
    "Install Now": http://www.telerik.com/products/reporting/download.aspx
    "Demos": https://demos.telerik.com/reporting
-
  title: "Support Resources"
  links: 
    "Contact Support": https://www.telerik.com/account/support-tickets
-
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/reporting
    "Blogs": http://www.telerik.com/blogs/tag/reporting
    "Feedback Portal": https://feedback.telerik.com/reporting
  
footer_social: 
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/ 
    twitter: https://twitter.com/Telerik/ 

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier
    gzip: false

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
